### ISSUE TITLE
vendored library "html5lib" does not support python3.10 and causes an error

### ISSUE THREAD

**Issue by PapuaHardyNet** [guildai/guildai#322]
### Issue

`guildai` vendors `html5lib`, which uses the import line `from collections import Mapping`, which does not work on `python3.10`. In `python3.10`, the import line should be `from collections.abc import Mapping`.

### Example error: 
```sh
% $HOME/.local/bin/guild run local-test:train
Traceback (most recent call last):
  File "/home/adrian/.local/bin/guild", line 8, in <module>
    sys.exit(main())
[...]
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/_tokenizer.py", line 16, in <module>
    from ._trie import Trie
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/_trie/__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/_trie/py.py", line 6, in <module>
    from ._base import Trie as ABCTrie
  File "/home/adrian/.local/lib/python3.10/site-packages/guild/external/pip/_vendor/html5lib/_trie/_base.py", line 3, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

This is fixed in the [upstream](https://github.com/html5lib/html5lib-python/blob/master/html5lib/_trie/_base.py).

### Solution

1. Manual fix: go to the vendored library file and change `from collections import Mapping` to `from collections.abc import Mapping`.
2. Downgrading: downgrade your python version to <3.10.
3. Update vendored dependencies: this ensures the vendored `html5lib` dependency works with `python3.10`.

`guildai` is great. I'd like to continue to be able to use it.

### Similar issues:
- https://github.com/flux-framework/flux-core/issues/4040
- https://github.com/pytest-dev/pytest-django/issues/985
- https://github.com/tensorflow/tensorboard/issues/5478

**Comment by msarahan** [comment]
This issue should be fixed now. Please try again, and if you encounter further issues, comment here. 

EDIT: that's true for the source code. If you're using the latest tagged release instead, you'll have to wait for a release.

**Comment by EvanCarroll** [comment]
@PapuaHardyNet  certainly that link behind "fixed" isn't the right one? That's from 2018. This was filed in Feb of 2022. It seems that's about supporting python2. I can confirm my own copy html5lib has that patch, but I'm still getting this problem with django.

**Comment by msarahan** [comment]
@EvanCarroll can you please post a separate issue with more details? Specifically, what guild ai version you're using, and since you seem to be having this problem with django, any version there. Any traceback you have would also be helpful.

**Comment by EvanCarroll** [comment]
Oh, just for clarity my issue isn't guildai. I'm not using this at all. I'm getting this error with the django. Which still has the issue open. I was just curious why you thought the `upstream` link above was related or has the fix. I think that was in error. That issue is unrelated to this one, afaik.

My guess is the core bug here still remains in `html5lib` and is unreported.
